services:
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - 8080:80
    volumes:
      - ./data/logs/nginx/:/var/log/nginx/

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    expose:
      - 9000
    env_file:
      - ".env"

  db:
    build:
      context: .
      dockerfile: docker/mysql/Dockerfile
    volumes:
      - mysql_data:/var/lib/mysql
    env_file:
      - ".env"

volumes:
  mysql_data:
