- name: Copy app
  ansible.builtin.copy:
    src: ../../../app/
    dest: /usr/share/example_app/app

- name: Copy .env file
  ansible.builtin.copy:
    src: ../../../.env
    dest: /usr/share/example_app/.env

- name: Copy docker files
  ansible.builtin.copy:
    src: ../../../docker/
    dest: /usr/share/example_app/docker

- name: Copy docker-compose.yml
  ansible.builtin.copy:
    src: ../../../docker-compose.yml
    dest: /usr/share/example_app/docker-compose.yml

- name: Generate nginx default.conf
  template:
    src: templates/nginx_conf.j2
    dest: /usr/share/example_app/docker/nginx/nginx.conf

- name: Generate nginx example_app.conf
  template:
    src: templates/nginx_example_app.j2
    dest: /usr/share/example_app/docker/nginx/example_app.conf
